// <auto-generated />
using BukeyWegRazor_temp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BukeyWegRazor_temp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327110027_IintialCreateOfRazorDb")]
    partial class IintialCreateOfRazorDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BukeyWegRazor_temp.Models.Catagory", b =>
                {
                    b.Property<int>("CatagoreyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatagoreyId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CatagoreyId");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CatagoreyId = 1,
                            DisplayOrder = 3,
                            Name = "Science"
                        },
                        new
                        {
                            CatagoreyId = 2,
                            DisplayOrder = 2,
                            Name = "History"
                        },
                        new
                        {
                            CatagoreyId = 3,
                            DisplayOrder = 1,
                            Name = "SciFi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
